name: Build
description: Build Alpine image
inputs:
  version:
    description: alpine version
    required: true
  dev:
    description: dev version of image
    required: false
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      ALPINE_VER: ${{ inputs.version }}
      ALPINE_DEV: ${{ inputs.dev }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
